canaza_bi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: canaza-dw-pg
      user: postgres
      password: postgres
      port: 5432
      dbname: canaza_dw
      schema: marts
      threads: 1