name: canaza-bi-dbt

services:
  dbt:
    build: .
    container_name: canaza-dw-dbt
    volumes:
      - .:/usr/app
      - ./.dbt:/root/.dbt
    working_dir: /usr/app
    command: sleep infinity
    networks:
      - canaza-bi-net
    tty: true
    stdin_open: true

networks:
  canaza-bi-net:
    external: true
    name: canaza-bi-net